name: Execute Testspec

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies and run tests
      run: |
        cd tests/
        npm config set strict-ssl false
        npm install
        npm i playwright-core
        npm run e2e:env

    - name: Generate test report
      run: |
        npm run generate-report

    - name: Upload test report
      uses: marvinpinto/action-automatic-releases@latest
      with:
        artifacts: tests/reports/detailed-report.html
        token: ${{ secrets.GITHUB_TOKEN }}

